baseURL: https://guilhermo.games/
languageCode: en-us
DefaultContentLanguage: en

publishDir: ../docs/
build:
  writeStats: true

languages:
  en:
    # baseURL: "/"
    languageName: English
    contentDir: content.en
    weight: 1
  pt-BR:
    # baseURL: "br/"
    languageName: Português
    contentDir: content.br
    weight: 2

# Allow html in .md files
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

params:
  relativeURLs: true
  title: Guilhermo Barretti
  # author: Darshan Baral
  # description: Website title
  # copyright: >-
  #   powered by [hugo](https://gohugo.io/) & deployed on
  #   [Cloudflare](https://www.cloudflare.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="shortcut icon" href="Icon.ico">
  profile:
    name: "Guilhermo Barretti"
    # tagline: Game Developer
    # location: "São José dos Campos, SP"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-github
        url: "https://github.com/GuilhermoBarretti"
        title: GitHub
      - icon: fab fa-twitter
        url: "https://twitter.com/guilhermodsb"
        title: Twitter
      - icon: fab fa-itch-io
        url: "https://guiks.itch.io/"
        title: Itch.io
      - icon: fab fa-instagram
        url: "https://instagram.com/guilhermobarretti"
        title: Instagram
      # - icon: fab fa-medium
      #   url: "https://guiks.medium.com/"
      #   title: Medium
      # - icon: fab fa-bsky
      #   url: "https://bsky.app/profile/guilhermo.bsky.social"
      #   title: BlueSky
      # - icon: fab fa-threads
      #   url: "http://threads.net/@guilhermobarretti"
      #   title: Threads
      # - icon: fab fa-mastodon
      #   url: "https://mastodon.gamedev.place/@guilhermo"
      #   title: Mastodon
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/guilhermo-barretti-304999236/"
        title: LinkedIn
  showInAccordion:
    - item: project
      expand: true
    - item: aboutme
    - item: education
    - item: skill
  aboutme:
    title: About Me
    icon: fas fa-user
    # description: "aboutMeDesc"
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Computer Science
        college: Universidade Federal de São Carlos
        dates: dateUfscar
      - degree: Computer Science
        college: Universidade Anhembi Morumbi
        dates: dateUAM
  project:
    title: My Games
    icon: fas fa-gamepad
    list:
      - title: titleGranolaJumps
        url: "/granolajumps"
        description: descGranolaJumps
        imageIcon: GranolaJumps.png
      - title: titleSTP
        url: "/savetheplanets"
        description: descSTP
        imageIcon: STP.png
      - title: titleIndigo
        url: "https://guiks.itch.io/indigo"
        description: descIndigo
        imageIcon: Indigo_Icon_Animated.gif
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: Unity
      - skill: C#
      - skill: C++
      - skill: OpenGL
      - skill: Lua
      - skill: Javascript
