const theme = require("tailwindcss/defaultTheme");

module.exports = {
	important: true,
	content: [
		"content/**/*.md",
		"layouts/**/*.html",
		"static/**/*.html",
		"./themes/**/layouts/**/*.html",
		"./content/**/layouts/**/*.html",
		"./layouts/**/*.html",
		"./content/**/*.html",
		'./static/**/*.html'
	],
	darkMode: "class", // 'media' or 'class'
	theme: {
		extend: {
			colors: {
				'nm-bg': '#5b4b87',
				'nm-dark': '#4d4073',
				'nm-light': '#645395',
				'h1': '#1f506c',
				'h2': '#1f506c',
				'link': '#0068a9',
				'text': '#000000',
				'hoverbg': '#8f8f8f',
				'profilename': '#8f8f8f',
				'socialIcon': '#c0c0c0',
			},
			backgroundColor: (theme) => ({
				body: '#7e9fb1',
				profilePhoto: '#1f506c',
				profileAccordion: '#a6a6a6',
				content: '#d9d9d9',
				quote: '#c0c0c0',
				// content: '#a9c4d3',

				// darkest: '#081720',
				// darker: '#0f2c3d',
				// dark: '#1f506c',
				// darker: '#123549',
				darkest: '#a6a6a6',
				darker: '#1f506c',
				dark: '#7a7a7a',
			}),
			typography: (theme) => ({
				DEFAULT: {
					css: {
						// "code::before": false,
						// "code::after": false,
						// a: {
						//   color: theme(`colors.blue.600`),
						//   textDecoration: "none",
						//   "&:hover": {
						//     color: theme(`colors.blue.800`),
						//     textDecoration: "underline",
						//   },
						// },
						pre: {
							backgroundColor: '#000000',
						},
						blockquote: {
							fontSize: '19px',
						},
						code: { color: theme(`colors.gray.700`) },
						'--tw-prose-captions': '#595959',
						'--tw-prose-quotes': '#000000',
						'--tw-prose-links': '#0068a9',
						'--tw-prose-headings': '#1f506c',
						'--tw-prose-body': '#000000',
						// '--tw-prose-headings': '#9ad1f3',
						// '--tw-prose-headings': '#a0c5db',
						'--tw-prose-counters': '#000000',
						// '--tw-prose-h1': '#ffffff',
						// '--tw-prose-h2': '#b8d2e1',
						// '--tw-prose-h3': '#b8d2e1',
						// '--tw-prose-headings': '#a0c5db',
						// '--tw-prose-headings': '#9ad1f3',
						// '--tw-prose-lead': theme('colors.pink[700]'),
						// '--tw-prose-links': theme('colors.pink[900]'),
						// '--tw-prose-bold': theme('colors.pink[900]'),
						// '--tw-prose-bullets': theme('colors.pink[400]'),
						// '--tw-prose-hr': theme('colors.pink[300]'),
						// '--tw-prose-quotes': theme('colors.pink[900]'),
						// '--tw-prose-quote-borders': theme('colors.pink[300]'),
						// '--tw-prose-code': '#00ffff',
						// '--tw-prose-pre-code': theme('colors.pink[100]'),
						// '--tw-prose-pre-bg': theme('colors.pink[900]'),
						// '--tw-prose-th-borders': theme('colors.pink[300]'),
						// '--tw-prose-td-borders': theme('colors.pink[200]'),
						// '--tw-prose-invert-body': theme('colors.pink[200]'),
						// '--tw-prose-invert-headings': theme('colors.white'),
						// '--tw-prose-invert-lead': theme('colors.pink[300]'),
						// '--tw-prose-invert-links': theme('colors.white'),
						// '--tw-prose-invert-bold': theme('colors.white'),
						// '--tw-prose-invert-counters': theme('colors.pink[400]'),
						// '--tw-prose-invert-bullets': theme('colors.pink[600]'),
						// '--tw-prose-invert-hr': theme('colors.pink[700]'),
						// '--tw-prose-invert-quotes': theme('colors.pink[100]'),
						// '--tw-prose-invert-quote-borders': theme('colors.pink[700]'),
						// '--tw-prose-invert-captions': theme('colors.pink[400]'),
						// '--tw-prose-invert-code': theme('colors.white'),
						// '--tw-prose-invert-pre-code': theme('colors.pink[300]'),
						// '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
						// '--tw-prose-invert-th-borders': theme('colors.pink[600]'),
						// '--tw-prose-invert-td-borders': theme('colors.pink[700]'),
					},
				},
				invert: {
					css: {
						//     color: theme(`colors.gray.200`),
						//     a: {
						//       color: theme(`colors.yellow.300`),
						//       "&:hover": { color: theme(`colors.yellow.500`) },
						//     },
						//     h1: { color: theme(`colors.gray.200`) },
						//     h2: { color: theme(`colors.gray.200`) },
						//     h3: { color: theme(`colors.gray.200`) },
						//     h4: { color: theme(`colors.gray.200`) },
						//     h5: { color: theme(`colors.gray.200`) },
						//     h6: { color: theme(`colors.gray.200`) },
						//     strong: { color: theme(`colors.gray.200`) },
						//     td: { color: theme(`colors.gray.200`) },
						//     blockquote: { color: theme(`colors.gray.200`) },
						pre: {
							backgroundColor: '#000000',
						},
						code: {
							color: '#ffffff'
						},
					},
				},
			}),
		},
	},
	variants: { typography: ["invert"], extend: {} },
	plugins: [require("@tailwindcss/typography")],
};
